# Generated by Django 4.2.6 on 2023-11-25 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='weekly_hours',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
