# Generated by Django 4.2.6 on 2023-12-01 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0004_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={},
        ),
        migrations.RemoveField(
            model_name='plan',
            name='max_date',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='name',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='user',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='weekly_hours',
        ),
    ]
