# Generated by Django 4.2.6 on 2023-12-01 21:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('goals', '0006_alter_plan_options_plan_max_date_plan_name_plan_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='max_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='objective',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='plan',
            name='weekly_hours',
            field=models.IntegerField(null=True),
        ),
    ]
