# Generated by Django 4.2.6 on 2023-12-01 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0019_delete_task'),
        ('goals', '0002_plan_weekly_hours'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Plan',
        ),
    ]
