# Generated by Django 4.2.6 on 2023-12-01 20:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('goals', '0005_alter_plan_options_remove_plan_max_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ['max_date']},
        ),
        migrations.AddField(
            model_name='plan',
            name='max_date',
            field=models.DateField(default = None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plan',
            name='name',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plan',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plan',
            name='weekly_hours',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
