# Generated by Django 4.2.6 on 2023-12-01 21:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('goals', '0007_alter_plan_max_date_alter_plan_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='max_date',
            field=models.DateField(default="2023-01-01"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='plan',
            name='name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='plan',
            name='objective',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='plan',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='plan',
            name='weekly_hours',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
