# Generated by Django 4.2.6 on 2023-12-02 01:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('goals', '0008_alter_plan_max_date_alter_plan_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='max_date',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='plan',
            name='name',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='plan',
            name='objective',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='plan',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='plan',
            name='weekly_hours',
            field=models.IntegerField(default=None),
        ),
    ]
