# Generated by Django 4.2.6 on 2023-11-09 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0014_alter_task_options_remove_task_complete_task_group_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='user_id',
            new_name='user',
        ),
    ]
