# Generated by Django 4.2.6 on 2023-12-01 20:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0006_alter_plan_options_plan_max_date_plan_name_plan_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo', '0021_alter_task_options_remove_task_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['status']},
        ),
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='group',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='hours',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='goals.plan'),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('NOT STARTED', 'Not Started'), ('DOING', 'Doing'), ('DONE', 'Done')], default='NOT STARTED', max_length=12),
        ),
        migrations.AddField(
            model_name='task',
            name='title',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
