# Generated by Django 4.2.6 on 2023-12-22 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0026_alter_task_date_alter_task_hours_alter_task_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateField(default=None),
        ),
    ]
